apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: 150387322390.dkr.ecr.ap-south-1.amazonaws.com/cowsay:latest
        ports:
        - containerPort: 4499
