name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1  # Update to your preferred AWS region

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Install kubectl
      run: |
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    # - name: Create EKS cluster
    #   run: |
    #     eksctl create cluster \
    #     --name wisecow-cluster \
    #     --region ap-south-1 \
    #     --nodegroup-name wisecow-nodes \
    #     --node-type t3.medium \
    #     --nodes 3 \
    #     --nodes-min 1 \
    #     --nodes-max 4 \
    #     --managed

    - name: Update kubeconfig
      run: |
        aws eks --region ap-south-1 update-kubeconfig --name wisecow-cluster

    - name: Wait for nodes to be ready
      run: |
        kubectl wait --for=condition=Ready node --all --timeout=600s

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f deployment.yaml --validate=false
        kubectl apply -f service.yaml --validate=false
        kubectl apply -f ingress.yaml --validate=false
